In [1]:
import numpy as np
#Arthmetic operations on 1-D arrays:
#addition:

arr1 = np.array([10,20,30,40,50])
arr2 = np.array([60,70,80,90,100])
print(arr1+arr2)
print(np.add(arr1,arr2))

[ 70  90 110 130 150]
[ 70  90 110 130 150]


In [2]:
#substraction:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([60,70,80,90,100])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[-50 -50 -50 -50 -50]
[-50 -50 -50 -50 -50]


In [3]:
#multiplication:

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[ 5 12 21 32]
[ 5 12 21 32]


In [5]:
#division:

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr1/arr2)

print(np.divide(arr1,arr2))

[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [6]:
# square root:

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[1.         1.41421356 1.73205081 2.        ]
[2.23606798 2.44948974 2.64575131 2.82842712]


In [7]:
#floor division: returns quotient 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr1//arr2)

print(np.floor_divide(arr1,arr2))

[0 0 0 0]
[0 0 0 0]


In [8]:
#modulus: returns reminder 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr1%arr2)

print(np.mod(arr1,arr2))

[1 2 3 4]
[1 2 3 4]


In [9]:
#Exponential:

arr1 = np.array([1,2,3,4])
print(arr1**5)

[   1   32  243 1024]


In [10]:
#Arthmetic operations on 2-D arrays:
#addition
arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.array([[19,29,39,49],[99,89,79,69]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 20  31  42  53]
 [109 109 109 109]]
[[ 20  31  42  53]
 [109 109 109 109]]


In [11]:
#subtaction:

arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.array([[19,29,39,49],[99,89,79,69]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[-18 -27 -36 -45]
 [-89 -69 -49 -29]]
[[-18 -27 -36 -45]
 [-89 -69 -49 -29]]


In [12]:
#multiplication:

arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.array([[19,29,39,49],[99,89,79,69]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[  19   58  117  196]
 [ 990 1780 2370 2760]]
[[  19   58  117  196]
 [ 990 1780 2370 2760]]


In [13]:
#division:
arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.array([[19,29,39,49],[99,89,79,69]])
print(arr1/arr2)

print(np.divide(arr1,arr2))

[[0.05263158 0.06896552 0.07692308 0.08163265]
 [0.1010101  0.2247191  0.37974684 0.57971014]]
[[0.05263158 0.06896552 0.07692308 0.08163265]
 [0.1010101  0.2247191  0.37974684 0.57971014]]


In [15]:
#floor division:
arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.array([[19,29,39,49],[99,89,79,69]])
print(arr1//arr2)

print(np.floor_divide(arr1,arr2))

[[0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]]


In [16]:
# square root:

arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.array([[19,29,39,49],[99,89,79,69]])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[[1.         1.41421356 1.73205081 2.        ]
 [3.16227766 4.47213595 5.47722558 6.32455532]]
[[4.35889894 5.38516481 6.244998   7.        ]
 [9.94987437 9.43398113 8.88819442 8.30662386]]


In [17]:
#modulus:

arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.array([[19,29,39,49],[99,89,79,69]])
print(arr1%arr2)

print(np.mod(arr1,arr2))

[[ 1  2  3  4]
 [10 20 30 40]]
[[ 1  2  3  4]
 [10 20 30 40]]


In [19]:
#Exponential:

arr1 = np.array([[1,2,3,4],[10,20,30,40]])
arr2 = np.array([[19,29,39,49],[99,89,79,69]])
print(arr1**5)
print(arr2**5)

[[        1        32       243      1024]
 [   100000   3200000  24300000 102400000]]
[[    2476099    20511149    90224199   282475249]
 [  919965907  1289092153 -1217910897  1564031349]]


In [20]:
#Arthmetic operations on 3-D arrays:
#addition
arr1 = np.array([[[41,68,49,65,22],[64,78,45,90,23]],
                 [[45,62,78,12,41],[56,89,34,56,23]],
                 [[46,78,56,23,12],[89,67,34,54,65]]]
                )
arr2 = np.array([[[83,36,23,99,14],[45,67,23,67,23]],
                 [[78,95,63,34,45],[67,34,23,13,15]],
                 [[89,56,34,76,83],[56,72,34,90,56]]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[[124 104  72 164  36]
  [109 145  68 157  46]]

 [[123 157 141  46  86]
  [123 123  57  69  38]]

 [[135 134  90  99  95]
  [145 139  68 144 121]]]
[[[124 104  72 164  36]
  [109 145  68 157  46]]

 [[123 157 141  46  86]
  [123 123  57  69  38]]

 [[135 134  90  99  95]
  [145 139  68 144 121]]]


In [21]:
#subtaction:

arr1 = np.array([[[41,68,49,65,22],[64,78,45,90,23]],
                 [[45,62,78,12,41],[56,89,34,56,23]],
                 [[46,78,56,23,12],[89,67,34,54,65]]]
                )
arr2 = np.array([[[83,36,23,99,14],[45,67,23,67,23]],
                 [[78,95,63,34,45],[67,34,23,13,15]],
                 [[89,56,34,76,83],[56,72,34,90,56]]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[[-42  32  26 -34   8]
  [ 19  11  22  23   0]]

 [[-33 -33  15 -22  -4]
  [-11  55  11  43   8]]

 [[-43  22  22 -53 -71]
  [ 33  -5   0 -36   9]]]
[[[-42  32  26 -34   8]
  [ 19  11  22  23   0]]

 [[-33 -33  15 -22  -4]
  [-11  55  11  43   8]]

 [[-43  22  22 -53 -71]
  [ 33  -5   0 -36   9]]]


In [22]:
#multiplication:

arr1 = np.array([[[41,68,49,65,22],[64,78,45,90,23]],
                 [[45,62,78,12,41],[56,89,34,56,23]],
                 [[46,78,56,23,12],[89,67,34,54,65]]]
                )
arr2 = np.array([[[83,36,23,99,14],[45,67,23,67,23]],
                 [[78,95,63,34,45],[67,34,23,13,15]],
                 [[89,56,34,76,83],[56,72,34,90,56]]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[[3403 2448 1127 6435  308]
  [2880 5226 1035 6030  529]]

 [[3510 5890 4914  408 1845]
  [3752 3026  782  728  345]]

 [[4094 4368 1904 1748  996]
  [4984 4824 1156 4860 3640]]]
[[[3403 2448 1127 6435  308]
  [2880 5226 1035 6030  529]]

 [[3510 5890 4914  408 1845]
  [3752 3026  782  728  345]]

 [[4094 4368 1904 1748  996]
  [4984 4824 1156 4860 3640]]]


In [23]:
#division:
arr1 = np.array([[[41,68,49,65,22],[64,78,45,90,23]],
                 [[45,62,78,12,41],[56,89,34,56,23]],
                 [[46,78,56,23,12],[89,67,34,54,65]]]
                )
arr2 = np.array([[[83,36,23,99,14],[45,67,23,67,23]],
                 [[78,95,63,34,45],[67,34,23,13,15]],
                 [[89,56,34,76,83],[56,72,34,90,56]]])

print(arr1/arr2)

print(np.divide(arr1,arr2))

[[[0.4939759  1.88888889 2.13043478 0.65656566 1.57142857]
  [1.42222222 1.1641791  1.95652174 1.34328358 1.        ]]

 [[0.57692308 0.65263158 1.23809524 0.35294118 0.91111111]
  [0.8358209  2.61764706 1.47826087 4.30769231 1.53333333]]

 [[0.51685393 1.39285714 1.64705882 0.30263158 0.14457831]
  [1.58928571 0.93055556 1.         0.6        1.16071429]]]
[[[0.4939759  1.88888889 2.13043478 0.65656566 1.57142857]
  [1.42222222 1.1641791  1.95652174 1.34328358 1.        ]]

 [[0.57692308 0.65263158 1.23809524 0.35294118 0.91111111]
  [0.8358209  2.61764706 1.47826087 4.30769231 1.53333333]]

 [[0.51685393 1.39285714 1.64705882 0.30263158 0.14457831]
  [1.58928571 0.93055556 1.         0.6        1.16071429]]]


In [24]:
# square root:

# square root:

arr1 = np.array([[[78,79,58],[76,86,75]],
                 [[46,33,22],[89,76,87]],
                 [[67,26,38],[96,35,35]]]
                )
arr2 = np.array([[[73,36,24],[64,47,24]],
                 [[88,95,65],[26,24,63]],
                 [[79,16,43],[55,22,34]]])
print(np.sqrt(arr1))
print(np.sqrt(arr2))
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[[[8.83176087 8.88819442 7.61577311]
  [8.71779789 9.2736185  8.66025404]]

 [[6.78232998 5.74456265 4.69041576]
  [9.43398113 8.71779789 9.32737905]]

 [[8.18535277 5.09901951 6.164414  ]
  [9.79795897 5.91607978 5.91607978]]]
[[[8.54400375 6.         4.89897949]
  [8.         6.8556546  4.89897949]]

 [[9.38083152 9.74679434 8.06225775]
  [5.09901951 4.89897949 7.93725393]]

 [[8.88819442 4.         6.55743852]
  [7.41619849 4.69041576 5.83095189]]]
[[[8.83176087 8.88819442 7.61577311]
  [8.71779789 9.2736185  8.66025404]]

 [[6.78232998 5.74456265 4.69041576]
  [9.43398113 8.71779789 9.32737905]]

 [[8.18535277 5.09901951 6.164414  ]
  [9.79795897 5.91607978 5.91607978]]]
[[[8.54400375 6.         4.89897949]
  [8.         6.8556546  4.89897949]]

 [[9.38083152 9.74679434 8.06225775]
  [5.09901951 4.89897949 7.93725393]]

 [[8.88819442 4.         6.55743852]
  [7.41619849 4.69041576 5.83095189]]]


In [25]:
#floor division:
#floor division:
arr1 = np.array([[[8,7,58],[6,6,5]],
                 [[4,3,22],[8,6,7]],
                 [[6,2,38],[9,5,3]]]
                )
arr2 = np.array([[[7,6,2],[4,4,4]],
                 [[8,5,6],[6,4,3]],
                 [[7,1,4],[5,2,4]]])

print(arr1//arr2)

print(np.floor_divide(arr1,arr2))
n =2
print(arr1//arr2)
print(arr1//n)
print(n//arr2)
print(np.floor_divide(arr1,arr2))

[[[ 1  1 29]
  [ 1  1  1]]

 [[ 0  0  3]
  [ 1  1  2]]

 [[ 0  2  9]
  [ 1  2  0]]]
[[[ 1  1 29]
  [ 1  1  1]]

 [[ 0  0  3]
  [ 1  1  2]]

 [[ 0  2  9]
  [ 1  2  0]]]
[[[ 1  1 29]
  [ 1  1  1]]

 [[ 0  0  3]
  [ 1  1  2]]

 [[ 0  2  9]
  [ 1  2  0]]]
[[[ 4  3 29]
  [ 3  3  2]]

 [[ 2  1 11]
  [ 4  3  3]]

 [[ 3  1 19]
  [ 4  2  1]]]
[[[0 0 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 2 0]
  [0 1 0]]]
[[[ 1  1 29]
  [ 1  1  1]]

 [[ 0  0  3]
  [ 1  1  2]]

 [[ 0  2  9]
  [ 1  2  0]]]


In [26]:
#modulus:
arr1 = np.array([[[41,68,49,65,22],[64,78,45,90,23]],
                 [[45,62,78,12,41],[56,89,34,56,23]],
                 [[46,78,56,23,12],[89,67,34,54,65]]]
                )
arr2 = np.array([[[83,36,23,99,14],[45,67,23,67,23]],
                 [[78,95,63,34,45],[67,34,23,13,15]],
                 [[89,56,34,76,83],[56,72,34,90,56]]])

print(arr1%arr2)


print(np.mod(arr1,arr2))

[[[41 32  3 65  8]
  [19 11 22 23  0]]

 [[45 62 15 12 41]
  [56 21 11  4  8]]

 [[46 22 22 23 12]
  [33 67  0 54  9]]]
[[[41 32  3 65  8]
  [19 11 22 23  0]]

 [[45 62 15 12 41]
  [56 21 11  4  8]]

 [[46 22 22 23 12]
  [33 67  0 54  9]]]
