In [1]:
!pip install numpy


In [37]:
import numpy as np

# creating a numpy:

a=np.array([1,2,3]) #1d= rows 
b=np.array([(1.5,2,3), (4,5,6)], dtype = float) #2d= rows, colmns
c=np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float) #3d= shape, rows, colmns.

print(a)

print(b)

print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [12]:
# intial placeholders:
# creating an array of zeros:

np.zeros((5))#rows



array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5,6))#rows,cols



array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
# creating array of ones:

np.ones((2,3,4))#shapes , rows, cols


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
# creating array of evenly spaced values(step values):

d=np.arange(7,25,3)
print(d)

[ 7 10 13 16 19 22]


In [23]:
# creating array of evenly spaced values:( number of values)

np.linspace(0,10,9)


array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [39]:
# creating a constant array:
# creating 1d array:

e=np.full((12),9)
print(e)
print("no of demension: ",e.ndim)

[9 9 9 9 9 9 9 9 9 9 9 9]
no of demension:  1


In [28]:
# creting 2d array:

e=np.full((12,23),45)
print(e)
print("no of demension: ",e.ndim)

[[45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]
 [45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45]]
no of demension:  2


In [27]:
# creating 3d array:

e=np.full((12,34,56),78)
print(e)
print("no of demension: ",e.ndim)

[[[78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  ...
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]]

 [[78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  ...
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]]

 [[78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  ...
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]]

 ...

 [[78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  ...
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]]

 [[78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  ...
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]]

 [[78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  ...
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]
  [78 78 78 ... 78 78 78]]]
no of deme

In [31]:
# creating a indentity matrix:

f=np.eye(123)
print(f)


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [32]:
# creating array with random values:

np.random.random((123,456))


array([[0.69158639, 0.48928317, 0.65350222, ..., 0.94219233, 0.15571078,
        0.48337245],
       [0.48020242, 0.99406364, 0.3430644 , ..., 0.02322194, 0.93069551,
        0.91812528],
       [0.09962401, 0.08701847, 0.2854322 , ..., 0.77135499, 0.19337762,
        0.71523426],
       ...,
       [0.86925527, 0.88855557, 0.46235204, ..., 0.57525278, 0.50217511,
        0.09515801],
       [0.2904032 , 0.79689665, 0.91651904, ..., 0.18416566, 0.02220551,
        0.697395  ],
       [0.78146104, 0.32821361, 0.50178973, ..., 0.82098705, 0.57157435,
        0.44397774]])

In [33]:
np.random.randint(123,456)


425

In [34]:
# to find the shape of array:

arr=np.array([[10,20,30,40],
              [12,23,34,45],
              [11,22,33,44]])
print(arr.shape)

(3, 4)


In [35]:
# to find the no. of elements in array:

arr=np.array([[10,20,30,40],
              [12,23,34,45],
              [11,22,33,44]])
print(arr.size)

12


In [36]:
# to find the length of array:

arr=np.array([[10,20,30,40],
              [12,23,34,45],
              [11,22,33,44]])
len(arr)

3