In [2]:
#Access array elements:

#you can access an array element by referring to its index number.
#The indexes in NumPy array start with 0. it means first element has index 0.

import numpy as np

arr =np.array([1,2,3,4,5,6])
print(arr[2])
print(arr[5])

3
6


In [3]:
#adding two index position.

arr = np.array([1,6,5,2,6,3])
print(arr[2]-arr[5]-arr[4])
print(arr[5]+arr[3]+arr[2])
print(arr[4]*arr[3])

-4
10
12


In [5]:
#Access 2-D arrays
#access the element on the first row , second column
arr = np.array([[1,2,3,4,5],[6,9,4,2,8],[5,2,7,8,4],[1,9,3,2,8]])
print('4nd element on 3rd row:', arr[3,4])

4nd element on 3rd row: 8


In [6]:
arr = np.array([[2,7,8],[9,3,4],[5,3,4]])
print('2nd element on 2nd row:', arr[2,2])

2nd element on 2nd row: 4


In [8]:
#Access 3-D Arrays
arr = np.array([[[1,2,3],
                 [4,5,6]],
                [[1,3,5],
                 [4,6,9]],
                [[1,2,3],
                 [4,7,4]],
                [[5,5,2],
                 [5,7,2]]])

#Access by index
print(arr[3,1,1]) #([2d,1d,element])
print(arr[1,0,1])
print(arr[2,0,2])

7
3
3


In [14]:
#Data Types:

#i - integer
#b - boolean
#u - unsigned(just like integers(whole numbers)but have the property that they dont have a + or - sign associated with them)
#f - float
#c - complex
#M - datetime
#O - Object
#S - String


In [15]:
#checking the datatype
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [16]:
#string
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [17]:
#Create an array with data type 4 bytes integer:

arr = np.array([1, 6, 3, 3], dtype='i4')
print(arr)
print(arr.dtype)

[1 6 3 3]
int32


In [18]:
#Change data type from float to integer by using 'i' as parameter value:

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [19]:
#Change data type from float to integer by using int as parameter value:

arr = np.array([1.5, 4.1, 8.6])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 4 8]
int32


In [20]:
#Change data type from integer to boolean:

arr = np.array([1, 0, 3, 7, 0, 8]) # 0 means false and all numbers 1-9 are true.
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True  True False  True]
bool


In [21]:
arr = np.array([1, 3, 0, 5])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True False  True]
bool


In [22]:
#changing into to float
arr = np.array([0,1,2,3,4])
x = arr.astype('f')
print(x)

[0. 1. 2. 3. 4.]


In [25]:
#changing float to unsigned integer
arr = np.array([0., 1.5, 2.5, 3.5, 4.5])
x = arr.astype('U')
print(x)

['0.0' '1.5' '2.5' '3.5' '4.5']


In [27]:
#changing int to unsigned integer
arr = np.array([0, 1, 2, 3, 4, 5])
x = arr.astype('U')
print(x)

['0' '1' '2' '3' '4' '5']


In [29]:
#changing float to complex float
arr = np.array([0.9, 1.6, 2.5, 2.7, 4.5])
x = arr.astype('c')
print(x)

[b'0' b'1' b'2' b'2' b'4']


In [30]:
#changing int to complex float
arr = np.array([1, 9, 6, 5, 3, 7])
x = arr.astype('c')
print(x)

[b'1' b'9' b'6' b'5' b'3' b'7']


In [31]:
#copy method: use to copy the data, it doesnt effect original data.

arr = np.array([123, 456, 789, 14, 25])
x = arr.copy()
arr[0] =  768
print(arr)
print(x)

[768 456 789  14  25]
[123 456 789  14  25]


In [32]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[4] =  768
print(arr)
print(x)

[  1   2   3   4 768]
[1 2 3 4 5]


In [33]:
#view method: it used to see the data, just like print()

arr = np.array([10,20,30,40,0])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42 20 30 40  0]
[42 20 30 40  0]


In [34]:
#shape : The shape of an array is the number of elements in each dimension.
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [35]:
#Create an array with 3 dimensions using ndmin using a 1 dimension array
arr = np.array([1, 2, 3, 4], ndmin=3)
print(arr)
print('shape of array :', arr.shape)

[[[1 2 3 4]]]
shape of array : (1, 1, 4)


In [37]:
#Reshaping arrays:

#Reshaping means changing the shape of an array.
#The shape of an array is the number of elements in each dimension.
#By reshaping we can add or remove dimensions or change number of elements in each dimension.


#converting the following 1-D array with 12 elements into a 2-D array.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)
print(arr)
print("*************************************************************")
newarr = arr.reshape(2,6)
print(newarr)

12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
*************************************************************
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [38]:
arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
newarr = arr.reshape(6, 2)
print(newarr)

[[ 1  5]
 [ 3  4]
 [ 5  3]
 [ 6  8]
 [ 8  9]
 [13 12]]


In [40]:
arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
newarr = arr.reshape(3,4 )
print(newarr)

[[ 1  5  3  4]
 [ 5  3  6  8]
 [ 8  9 13 12]]


In [41]:
#Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(1, 6, 2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:
arr = np.array([5, 6, 3, 4, 5, 3, 7, 8, 8, 9, 13, 11, 8,6,9,5,0,3,2,1])
newarr = arr.reshape(5, 2, 2)
print(arr)
print("*************************************************************")
print(newarr)

[ 5  6  3  4  5  3  7  8  8  9 13 11  8  6  9  5  0  3  2  1]
*************************************************************
[[[ 5  6]
  [ 3  4]]

 [[ 5  3]
  [ 7  8]]

 [[ 8  9]
  [13 11]]

 [[ 8  6]
  [ 9  5]]

 [[ 0  3]
  [ 2  1]]]


In [45]:
#converting 2 -D array to 1 -D array
arr = np.array([[1,2,3],[4,5,6]])
x= arr.reshape(arr.size)
print(x)

[1 2 3 4 5 6]


In [46]:
#converting 2 - D to 3 - D array

arr = np.array([[1,5,6,4,5,3],[4,3,7,9,2,5],[4,1,2,6,3,1]])
print(arr.size)
x= arr.reshape(3,2,3)
print(x)
print("*************************************************************")
y= arr.reshape(3,3,2)
print(y)
print("*************************************************************")
z= arr.reshape(2,3,3)
print(z)

18
[[[1 5 6]
  [4 5 3]]

 [[4 3 7]
  [9 2 5]]

 [[4 1 2]
  [6 3 1]]]
*************************************************************
[[[1 5]
  [6 4]
  [5 3]]

 [[4 3]
  [7 9]
  [2 5]]

 [[4 1]
  [2 6]
  [3 1]]]
*************************************************************
[[[1 5 6]
  [4 5 3]
  [4 3 7]]

 [[9 2 5]
  [4 1 2]
  [6 3 1]]]


In [47]:
#converting 3-D array to 1-D array
arr = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]],
                [[13,14,15],[16,17,18]]])
print(arr.size)
print(arr)
print("*************************************************************")
x= arr.reshape(arr.size)
print(x)

18
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
*************************************************************
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [51]:
#converting 3-D array to 2-D array
arr = np.array([[[1,4,5],[3,6,4]],
                [[3,7,6],[4,6,2]],
                [[6,7,3],[9,6,0]]])
print(arr.size)
print(arr)
print("*************************************************************")
x= arr.reshape(1,18)
print(x)
print("*********************************")
x= arr.reshape(2,9)
print(x)

18
[[[1 4 5]
  [3 6 4]]

 [[3 7 6]
  [4 6 2]]

 [[6 7 3]
  [9 6 0]]]
*************************************************************
[[1 4 5 3 6 4 3 7 6 4 6 2 6 7 3 9 6 0]]
*********************************
[[1 4 5 3 6 4 3 7 6]
 [4 6 2 6 7 3 9 6 0]]


In [52]:
#python program to create a datatype object

x= np.array([[1,2],[3,4]], dtype =np.float64)
print(x)
print("****************")
y = np.array([[5,6],[7,8]], dtype = np.float64)
print(y)

[[1. 2.]
 [3. 4.]]
****************
[[5. 6.]
 [7. 8.]]


In [53]:
#sorting arrays
#Sorting means putting elements in an ordered sequence.
#Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
#The NumPy ndarray object has a function called sort(), that will sort a specified array.

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [54]:
arr = np.array([[[1,4,5],[3,6,4]],
                [[3,7,6],[4,6,2]],
                [[6,7,3],[9,6,0]]])
print(np.sort(arr))

[[[1 4 5]
  [3 4 6]]

 [[3 6 7]
  [2 4 6]]

 [[3 6 7]
  [0 6 9]]]


In [55]:
#SLicing arrays:
#Slicing in python means taking elements from one given index to another given index.
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step].
#If we don't pass start its considered 0
#If we don't pass end its considered length of array in that dimension
#If we don't pass step its considered 1.

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])#n-1

[2 3 4 5]


In [58]:
arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[3:8])

[4 5 3 6 8]


In [62]:
#Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

# from 0 to end of array:
print(arr[:])

print("******************")
print(arr[:7])

[5 6 7]
[1 2 3 4 5 6 7]
******************
[1 2 3 4 5 6 7]


In [63]:
#Negative Slicing : Use the minus operator to refer to an index from the end
#Slice from the index 3 from the end to index 1 from the end:

arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[-7:-1])


[ 3  6  8  8  9 13]


In [64]:
#step : Use the step value to determine the step of the slicing
#Return every other element from index 1 to index 5:

arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[1:5:2])

[5 4]


In [65]:
#Return every other element from the entire array:


arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[::2])


[ 1  3  5  6  8 13]


In [66]:
#Slicing 2-D Arrays:

#From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [67]:
arr = np.array([[1,5,6,4,5,3],[4,3,7,9,2,5],[4,1,2,6,3,1]])
print(arr[0:3, 2:4])
print("*******************")
print(arr[:,:])

[[6 4]
 [7 9]
 [2 6]]
*******************
[[1 5 6 4 5 3]
 [4 3 7 9 2 5]
 [4 1 2 6 3 1]]


In [68]:
arr = np.array([[1,5,6,4,5,3],[4,3,7,9,2,5],[4,1,2,6,3,1]])
print(arr[0:2,3])
print(arr[0:6,1])

[4 9]
[5 3 1]


In [69]:
t = np.array([[2,4,6,2],[5,7,2,8],[9,4,2,4]])
print(t[0:4,2])

[6 2 2]


In [70]:
#slicing 3D arrays:

arr = np.array([[[1,2,3,4],[5,6,7,8]],
                [[3,7,6,8,4,5],[10,20,30,40]],
                [[6,7,3,7,8,9],[9,6,0,2,9,4]]])
print(arr[0,0:4,1:4])
print("**************")
print(arr[:,:,:])

[[4 5 6]
 [6 4 7]]
**************
[[[1 4 5 6 7 8]
  [3 6 4 7 2 6]]

 [[3 7 6 8 4 5]
  [4 6 2 4 9 3]]

 [[6 7 3 7 8 9]
  [9 6 0 2 9 4]]]
